### PR TITLE
Add "Install with Yunohost" button

### PR DESCRIPTION
**Pull request by lapineige**
See https://github.com/YunoHost/install-app

### CODE REVIEW

**Comment by alexAubin** [comment]
Bump ? Easy to merge PR :D

**Comment by julienmalik** [comment]
Seems like there is a typo for dokuwiki

**Comment by lapineige** [comment]
My bad, I always make this mistake :/
Fixed :)

**Comment by JimboJoe** [comment]
Will you find the remaining typo...? :wink:

**Comment by lapineige** [comment]
I can do it ^^
Fixed :)

**Pull request merged**
