### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- Package was outdated and needed work

## Solution
- Refactor following https://github.com/YunoHost/example_ynh
- Improve package
    - Use a local file to store Yunohost customization : https://www.dokuwiki.org/config#configuration_files
    - Upgrade Dokuwiki version to latest available : https://www.dokuwiki.org/changes
    - Add language choice from manifest
    - Fix Dokuwiki licence in manifest (GPL2)
    - Fix dokuwiki cleaning post update
        - Step 5 here : https://www.dokuwiki.org/install:upgrade
    - Cleaning of "sudo" and old files

## PR Status
- [X] Code finished.
- [X] Tested with Package_check.
- [X] Fix or enhancement tested.
- [X] Upgrade from last version tested.
- [X] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : frju365
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/dokuwiki_ynh%20testing%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Shall we wait for a stable CI to merge #39 and eventually release that wonderful job by @Gofannon ?

**Comment by maniackcrudelis** [comment]
I'm not sure to understand why you want to wait for the CI before merging this. PR aren't dependent of stable CI.

**Comment by JimboJoe** [comment]
Well #39 was about the README file and the links to the results of the CI (including full console)... and that links are not all verifiable at the moment :wink:

**Comment by Gofannon** [comment]
https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/40 should be merged before releasing this PR in master.
Will try to test event if changes are small and seems harmless

**Comment by Gofannon** [comment]
https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/40 can be reviewed as it has been tested by myself (and it needs other people to mess with it :) )

**Comment by Gofannon** [comment]
This PR can be reviewed. It is independent of https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/39 which needs some editing if I understand correctly

**Comment by maniackcrudelis** [comment]
The last commit was 7 days ago, can now be reviewed.

**Comment by maniackcrudelis** [comment]
Code review OK.
But just a quick review, I trust our reviews from https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/37 and https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/40

**Comment by frju365** [comment]
Will be merged in 3 days !

**Comment by Gofannon** [comment]
Hello. Something else needed or this PR has been forgotten?

**Comment by frju365** [comment]
No, just forgot the PR :/

**Pull request merged**
