### PR TITLE
Upgrade to v2020-07-31a

### PR DESCRIPTION
**Pull request by tituspijean**
⚠️ XSS vulnerability fix https://www.dokuwiki.org/changes#release_2022-07-31a_igor

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
@Gofannon ooops I forgot about #92 
I guess we need to merge this into this PR?

**Comment by Gofannon** [comment]
> @Gofannon ooops I forgot about #92 I guess we need to merge #93 into this PR #92?

@tituspijean ahaha, no worries. Yes, it should be better to use PR #92 first. I even put your changes in PR #92 so I think that this PR can be closed if you agree.

PR #92 is ready to review as it "runs on my server ©"

**Comment by tituspijean** [comment]
Superseded by #92.

**Pull request closed without merging**
