### PR TITLE
Merge from Testing

### PR DESCRIPTION
**Pull request by Gofannon**
* Remove ask on manifest
* Add ynh_abort_if_errors
* Fix documentation links
* Fix requirements in manifest.json

## PR Status
- [X] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

### CODE REVIEW

**Comment by Gofannon** [comment]
!testme

**Review by alexAubin — DISMISSED** [review]
LGTM :+1:

**Comment by alexAubin** [comment]
Bumpity bump, shall we merge this ?

**Review by yalh76 — DISMISSED** [review]

**Comment by yalh76** [comment]
Ready for level 9

**Pull request merged**
