### PR TITLE
dokuwiki - Updated to Elenor of Tsort

### PR DESCRIPTION
**Pull request by alexjj**
Tested on demo server: https://demo.yunohost.org/tsort/doku.php (perhaps it gets wiped) but you can install from my repo. 
1.  Added new dokuwiki source
2. Updated ldap config syntax in config file as new dokuwiki version has changed this.

### CODE REVIEW

**Comment by opi** [comment]
Hi, thanks for this PR ! Did you try both installing and updating ?

**Comment by alexjj** [comment]
I tried installing. I didn't try updating (via yunohost vs. via dokuwiki plugin?). 

Guess you'd need to use sed or something to adjust the config without overwriting the user's other config setup.

**Comment by opi** [comment]
finally find some time to test your pull-request. Upgrade and installing went fine, thanks !

My only little concern was about some removed plugins (captcha, gallery, translation, upgrade, vshare and wrap). I need to find a better way to include sources (wget or git clone from upstream). No worry, I add them back with d03777626 . Thankss again !!

**Comment by alexjj** [comment]
You're welcome! I left the dokuwiki install as the default that they ship, which I guess doesn't include those plugins. If someone upgrades and has those plugins I think they'll remain there? If someone is installing a new dokuwiki instance, not having those plugins shouldn't matter and they can install them.

As long as the LDAP plugin doesn't change config again, the self updating plugin should continue to work for everyone.

**Comment by opi** [comment]
you're right, existing plugins are kept, but not updated. I'd like the dokuwiki_ynh app to provide some popular plugins to allow non-tech end user to use them without having to do any ssh/ftp. 

And I can't agree more that the most important plugin is the LDAP one ;)

**Pull request merged**
