### PR TITLE
Igor

### PR DESCRIPTION
**Pull request by Gofannon**
## Problem

- New release : 2022-07-31 "Igor"

## Solution

- *And how do you fix that problem*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Gofannon** [comment]
!testme

**Comment by Gofannon** [comment]
!testme

**Comment by Gofannon** [comment]
@YunoHost-Apps/apps-group, some questions:

1. CI is "lying" about the failed "install in private" mode. It works when I install the branch manually. Any ideas of what is happening? I will push it anyway because it "works on my server"
2. What does this code do? https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/92/commits/26a16c44d0c58d1413c6c7beb5ca45ecfcf7ddfd I have no idea reading the "example_ynh" package but I used it anyway
3. I plan to "backport" to example_ynh my troubles for handling "PHP in a package". Is a PR on the example_ynh package the right place to discuss this? (using "extra_php-fpm.conf" for example)

**Comment by tituspijean** [comment]
> 1. CI is "lying" about the failed "install in private" mode. It works when I install the branch manually. Any ideas of what is happening? I will push it anyway because it "works on my server"

It's a long standing bug in the dev CI. You can safely ignore it.

> What does this code do? https://github.com/YunoHost-Apps/dokuwiki_ynh/commit/26a16c44d0c58d1413c6c7beb5ca45ecfcf7ddfd I have no idea reading the "example_ynh" package but I used it anyway

As stated in the command, you can remove it if there's nothing weird you did with the app that you need to cleanup with a custom function. I personally never saw it used in production. I sometimes use it in development with a `read -p "debug me"` to hold the removal script and give me time to investigate whenever a script fails.

> I plan to "backport" to example_ynh my troubles for handling "PHP in a package". Is a PR on the example_ynh package the right place to discuss this? (using "extra_php-fpm.conf" for example)

Sure, we will see with the other team members if we should showcase this code in the example app.

**Comment by Gofannon** [comment]
!testme

**Comment by Gofannon** [comment]
!testme

**Comment by Gofannon** [comment]
Tested on my server, it's fine to me. Code can be reviewed.
For changes, see the [Changelog](https://github.com/YunoHost-Apps/dokuwiki_ynh/blob/31825890144773a1e0ee338c7341026e32cfff79/CHANGELOG.md). If I miss to write something, you can add it to the changelog directly

**Comment by Gofannon** [comment]
I have no solution for implementing fail2ban for now. I posted on the dokuwiki forum about this and need to spend time on it : https://forum.dokuwiki.org/d/20414-protection-against-bruteforce-login
On the yunohost side, do "ldap logins" made by dokuwiki are monitored by fail2ban? This way, no need to put it in dokuwiki as it could be handled by yunohost directly

**Review by tituspijean — APPROVED** [review]
LGTM, let's move to testing.

**Pull request merged**
