### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Gofannon**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Gofannon** [comment]
!testme

**Review by OniriCorpe — DISMISSED** [review]
looks fine
have you tested it by hand?

**Comment by Gofannon** [comment]
> have you tested it by hand?

No. I don't anymore. Because of theses reasons:
1. time is missing
2. changes in this PR are minors
3. I used to test the 'testing' branch on my production server but:
    1. as there was "multiple iterations" applied to my server before getting a "stable version", the "test" was not really relevant anymore - multiple upgrades chained can lead to problems unseen.
    2. "testing" branch is not really used from my understanding (not tested by other people than me and communicating on the forum about it was time consuming )
    3. After my test, I was "stuck" on my "test branch" and YunoHost did not use the "normal version" from this repository and I did not realize it. I had to do a `yunohost app upgrade dokuwiki --force` to realign the package on my server with this repository.

**Comment by OniriCorpe** [comment]
so merging?

**Review by OniriCorpe — APPROVED** [review]

**Comment by Gofannon** [comment]
> so merging?

Yes. Done, thanks !

**Pull request merged**
