### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Get rid of the ini file and merge its content into the pool file.*

- *Global upgrade of the package.*

- *Update `Readme` following last work made on the package and current version in `testing` branch*

- *Nothing to prevent brute force*

## Solution
* Languages : English and French
* Update to reflect current state of package
* File taken from the forum and post [[Official app] Dokuwiki](https://forum.yunohost.org/t/official-app-dokuwiki/5366)
* Add Fail2ban

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [x] **Approval (LGTM)** : JimboJoe
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/dokuwiki_ynh%20PR49/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by Gofannon** [comment]
bump

**Comment by kay0u** [comment]
Ready for review?

**Comment by maniackcrudelis** [comment]
Huh yep probably...

**Comment by JimboJoe** [comment]
Can be merged in 3 days.

**Pull request merged**
