### PR TITLE
Permissions

### PR DESCRIPTION
**Pull request by Gofannon**
## Problem
- Permission system from 3.7 lacking

## Solution
- Implement new permission by following
  - https://github.com/YunoHost/example_ynh/pull/111/files and 
  - https://yunohost.org/#/groups_and_permissions_en
  - https://moulinette.readthedocs.io/en/latest/ldap.html#ldap-integration-in-yunohost-applications

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** :  
*Code review and approval have to be from a member of @YunoHost-Apps/apps-group*
- **CI succeeded** :
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/dokuwiki_ynh%20PR64/)

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by Gofannon** [comment]
Error while upgrade is because of this on the CI:
`Warning: yunohost.hook <lambda> - [1188.1] rm: cannot remove 'vendor/easybook/geshi': Directory not empty`

Piece of code related is here: https://github.com/YunoHost-Apps/dokuwiki_ynh/blob/testing/scripts/upgrade#L222

The file `deleted.files` can be found [on the dokuwiki repo](https://raw.githubusercontent.com/splitbrain/dokuwiki/stable/data/deleted.files) and there is a folder to remove `vendor/easybook/geshi`, not just files.

That's why `rm` complains. I will change `rm `options

So back to this comment I guess https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/47/files/d884f346183ac63695ceee343266a2ac4ed5f776..dc6168a0e305ccceb9c8958ee1242ae923dba8c3#diff-44cb16c778719320333118c04d509a7c

**Comment by maniackcrudelis** [comment]
Maybe that helper may help you https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_secure_remove_regex/ynh_secure_remove_regex

**Comment by Gofannon** [comment]
After trying different permutations, I cannot make it run with `ynh_secure_remove`.

----

With this kind of code:

```bash
cd $final_path

#grep --extended-regexp --invert-match '^($|#)' data/deleted.files | xargs --max-args=1 rm --verbose --force --dir 2>&1 || true

grep --extended-regexp --invert-match '^($|#)' data/deleted.files | xargs --max-args=1 ynh_secure_remove --file 2>&1

#grep --null --extended-regexp --invert-match '^($|#)' data/deleted.files > toto.list
#xargs --null --verbose --max-args=1 --arg-file=toto.list ynh_secure_remove 2>&1
```
I always end up in the upgrade logs

```bash
2020-08-25 12:26:42,156: INFO - [##########+++.......] > Upgrading dokuwiki...
2020-08-25 12:26:42,157: DEBUG - + cd /var/www/dokuwiki
2020-08-25 12:26:42,158: DEBUG - + grep --extended-regexp --invert-match '^($|#)' data/deleted.files
2020-08-25 12:26:42,159: DEBUG - + xargs --max-args=1 ynh_secure_remove --file
2020-08-25 12:26:42,260: DEBUG - xargs: ynh_secure_remove: Aucun fichier ou dossier de ce type
2020-08-25 12:26:42,261: DEBUG - + ynh_exit_properly
2020-08-25 12:26:42,263: DEBUG - + local exit_code=127
2020-08-25 12:26:42,264: DEBUG - + '[' 127 -eq 0 ']'
```

**Extract of `man xargs`**

       xargs exits with the following status:
       0 if it succeeds
       123 if any invocation of the command exited with status 1-125
       124 if the command exited with status 255
       125 if the command is killed by a signal
       126 if the command cannot be run
       127 if the command is not found
       1 if some other error occurred.

After searching, I found this : https://github.com/koalaman/shellcheck/wiki/SC2033

So, I guess, i's not possible to do it easily ?

I'm out of ideas and will [switch back to `rm -rf`](https://github.com/YunoHost-Apps/dokuwiki_ynh/pull/47/files/d884f346183ac63695ceee343266a2ac4ed5f776..dc6168a0e305ccceb9c8958ee1242ae923dba8c3#diff-44cb16c778719320333118c04d509a7c). As the input list is provided by DokuWiki itself, it should be trusted IMO.

( I spent too much time on this... )

**Comment by Gofannon** [comment]
Test passed on https://ci-apps-dev.yunohost.org/jenkins/job/dokuwiki_ynh%20(gofannon)/2/console

**Review by yalh76 — APPROVED** [review]
LGTM

**Comment by Gofannon** [comment]
After discussing with Alex, the way to manage the new permissions is not ready yet. PR on hold until decision has been made

**Review by zamentur — DISMISSED** [review]
LGTM

**Review by zamentur — APPROVED** [review]
LGTM

**Pull request merged**
